
services:

  pwntools:
    build: ./pwntools
    volumes:
      - ./pwntools/home:/home/pwntools:ro
    ports:
      - "9999:1337"
    expose:
      - "1337"

  bof:
    build: ./bof
    volumes:
      - ./bof/home:/home/bof:ro
    ports:
      - "10000:1337"
    expose:
      - "1337"

  bof2:
    build: ./bof2
    volumes:
      - ./bof2/home:/home/bof2:ro
    ports:
      - "10001:1337"
    expose:
      - "1337"

  ret2sc:
    build: ./ret2sc
    volumes:
      - ./ret2sc/home:/home/ret2sc:ro
    ports:
      - "10002:1337"
    expose:
      - "1337"

  gothijack:
    build: ./gothijack
    volumes:
      - ./gothijack/home:/home/gothijack:ro
    ports:
      - "10003:1337"
    expose:
      - "1337"

  rop:
    build: ./rop
    volumes:
      - ./rop/home:/home/rop:ro
    ports:
      - "10004:1337"
    expose:
      - "1337"

  ret2plt:
    build: ./ret2plt
    volumes:
      - ./ret2plt/home:/home/ret2plt:ro
    ports:
      - "10005:1337"
    expose:
      - "1337"

  ret2libc:
    build: ./ret2libc
    volumes:
      - ./ret2libc/home:/home/ret2libc:ro
    ports:
      - "10006:1337"
    expose:
      - "1337"

  sort:
    build: ./sort
    volumes:
      - ./sort/home:/home/sort:ro
    ports:
      - "10007:1337"
    expose:
      - "1337"
